export const START_FETCH_ALL_FILMS = 'START_FETCH_ALL_FILMS';
export const ALL_FILMS_FETCHED = 'ALL_FILMS_FETCHED';
export const FETCH_ALL_FILMS_FAILED = 'FETCH_ALL_FILMS_FAILED';
export const UPDATE_FILMS = 'UPDATE_FILMS';
export const FETCH_FILM = 'FETCH_FILM';